framework:
  outbox:
    enabled: ${FRAMEWORK_OUTBOX_ENABLED:true}
    serializer: ${FRAMEWORK_OUTBOX_SERIALIZER:defaultSerializer}
    auto:
      register:
        schemas: ${FRAMEWORK_OUTBOX_AUTO_REGISTER_SCHEMAS:true}