quarkus:

  profile: ${ENVIRONMENT:dev}

  container-image:
    push: false
    build: false
    image: ${IMAGE_URL:default}:${IMAGE_TAG:default}

  log:
    sentry:
      ~: false
    level: DEBUG
    category:
      org.redisson.connection.DNSMonitor:
        level: INFO
      org.mongodb.driver.cluster:
        level: INFO

  redis:
    hosts: ${REDIS_HOSTS:redis://localhost:6379}
    client-type: ${REDIS_CLIENT_TYPE:standalone}
    health:
      enabled: ${REDIS_HEALTH_ENABLED:false}
  hibernate-orm:
    database:
      globally-quoted-identifiers: true
  opentelemetry:
    enabled: ${OTEL_ENABLED:false}
    tracer:
      sampler:
        ratio: ${OTEL_SAMPLER_RATIO:0.3}
      exporter:
        otlp:
          endpoint: ${OTEL_ENDPOINT:https://otlp.nr-data.net}
          compression: ${OTEL_COMPRESSION:gzip}
          headers: ${OTEL_HEADERS:api-key=qwerty}
      resource-attributes: ${OTEL_RESOURCE_ATTRIBUTES:service.name=dev}

  ssl:
    native: true

framework:

  redis:
    enabled: ${FRAMEWORK_REDIS_ENABLED:true}
    defaultExpiryInMilli: ${FRAMEWORK_REDIS_DEFAULTEXPIRYINMILLI:10000}

  mongodb:
    enabled: ${FRAMEWORK_MONGODB_ENABLED:true}

  sql:
    enabled: ${FRAMEWORK_SQL_ENABLED:true}

  rollbar:
    enabled: ${FRAMEWORK_ROLLBAR_ENABLED:false}
